[build]
  publish = "."
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

# Environment variables (set these in Netlify dashboard)
[context.production.environment]
  SERPAPI_KEY = "your_production_serpapi_key"
  AMAZON_AFFILIATE_TAG = "your_production_amazon_tag"
  STRIPE_SECRET_KEY = "your_production_stripe_key"

[context.deploy-preview.environment]
  SERPAPI_KEY = "your_staging_serpapi_key"
  AMAZON_AFFILIATE_TAG = "your_staging_amazon_tag"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"